{
  "version": "2.1.1",
  "name": "check-error",
  "description": "Error comparison and information related utility for node and the browser",
  "keywords": [
    "check-error",
    "error",
    "chai util"
  ],
  "license": "MIT",
  "author": {
    "name": "Jake Luer",
    "email": "jake@alogicalparadox.com",
    "url": "http://alogicalparadox.com"
  },
  "contributors": [
    {
      "name": "David Losert",
      "url": "https://github.com/davelosert"
    },
    {
      "name": "Keith Cirkel",
      "url": "https://github.com/keithamus"
    },
    {
      "name": "Miroslav BajtoÅ¡",
      "url": "https://github.com/bajtos"
    },
    {
      "name": "Lucas Fernandes da Costa",
      "url": "https://github.com/lucasfcosta"
    }
  ],
  "files": [
    "index.js",
    "check-error.js"
  ],
  "type": "module",
  "main": "./index.js",
  "module": "./index.js",
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/chaijs/check-error.git"
  },
  "scripts": {
    "lint": "eslint --ignore-path .gitignore index.js test/",
    "semantic-release": "semantic-release pre && npm publish && semantic-release post",
    "pretest": "npm run lint",
    "test": "npm run test:node && npm run test:browser",
    "test:browser": "web-test-runner",
    "test:node": "mocha"
  },
  "config": {
    "ghooks": {
      "commit-msg": "validate-commit-msg"
    }
  },
  "eslintConfig": {
    "extends": [
      "strict/es6"
    ],
    "env": {
      "es6": true
    },
    "globals": {
      "HTMLElement": false
    },
    "rules": {
      "complexity": "off",
      "max-statements": "off",
      "prefer-arrow-callback": "off",
      "prefer-reflect": "off"
    }
  },
  "devDependencies": {
    "@web/test-runner": "^0.17.0",
    "browserify": "^13.0.0",
    "browserify-istanbul": "^1.0.0",
    "eslint": "^2.4.0",
    "eslint-config-strict": "^8.5.0",
    "eslint-plugin-filenames": "^0.2.0",
    "ghooks": "^1.0.1",
    "mocha": "^9.1.2",
    "semantic-release": "^4.3.5",
    "simple-assert": "^2.0.0",
    "validate-commit-msg": "^2.3.1"
  },
  "engines": {
    "node": ">= 16"
  },
  "readme": "<h1 align=center>\n  <a href=\"http://chaijs.com\" title=\"Chai Documentation\">\n    <img alt=\"ChaiJS\" src=\"http://chaijs.com/img/chai-logo.png\">\n  </a>\n  <br>\n  check-error\n</h1>\n\n<p align=center>\n  Error comparison and information related utility for <a href=\"http://nodejs.org\">node</a> and the browser.\n</p>\n\n## What is Check-Error?\n\nCheck-Error is a module which you can use to retrieve an Error's information such as its `message` or `constructor` name and also to check whether two Errors are compatible based on their messages, constructors or even instances.\n\n## Installation\n\n### Node.js\n\n`check-error` is available on [npm](http://npmjs.org). To install it, type:\n\n    $ npm install check-error\n\n### Browsers\n\nYou can also use it within the browser; install via npm and use the `check-error.js` file found within the download. For example:\n\n```html\n<script src=\"./node_modules/check-error/check-error.js\"></script>\n```\n\n## Usage\n\nThe primary export of `check-error` is an object which has the following methods:\n\n* `compatibleInstance(err, errorLike)` - Checks if an error is compatible with another `errorLike` object. If `errorLike` is an error instance we do a strict comparison, otherwise we return `false` by default, because instances of objects can only be compatible if they're both error instances.\n* `compatibleConstructor(err, errorLike)` - Checks if an error's constructor is compatible with another `errorLike` object. If `err` has the same constructor as `errorLike` or if `err` is an instance of `errorLike`.\n* `compatibleMessage(err, errMatcher)` - Checks if an error message is compatible with an `errMatcher` RegExp or String (we check if the message contains the String).\n* `getConstructorName(errorLike)` - Retrieves the name of a constructor, an error's constructor or `errorLike` itself if it's not an error instance or constructor.\n* `getMessage(err)` - Retrieves the message of an error or `err` itself if it's a String. If `err` or `err.message` is undefined we return an empty String.\n\n```js\nvar checkError = require('check-error');\n```\n\n#### .compatibleInstance(err, errorLike)\n\n```js\nvar checkError = require('check-error');\n\nvar funcThatThrows = function() { throw new TypeError('I am a TypeError') };\nvar caughtErr;\n\ntry {\n  funcThatThrows();\n} catch(e) {\n  caughtErr = e;\n}\n\nvar sameInstance = caughtErr;\n\ncheckError.compatibleInstance(caughtErr, sameInstance); // true\ncheckError.compatibleInstance(caughtErr, new TypeError('Another error')); // false\n```\n\n#### .compatibleConstructor(err, errorLike)\n\n```js\nvar checkError = require('check-error');\n\nvar funcThatThrows = function() { throw new TypeError('I am a TypeError') };\nvar caughtErr;\n\ntry {\n  funcThatThrows();\n} catch(e) {\n  caughtErr = e;\n}\n\ncheckError.compatibleConstructor(caughtErr, Error); // true\ncheckError.compatibleConstructor(caughtErr, TypeError); // true\ncheckError.compatibleConstructor(caughtErr, RangeError); // false\n```\n\n#### .compatibleMessage(err, errMatcher)\n\n```js\nvar checkError = require('check-error');\n\nvar funcThatThrows = function() { throw new TypeError('I am a TypeError') };\nvar caughtErr;\n\ntry {\n  funcThatThrows();\n} catch(e) {\n  caughtErr = e;\n}\n\nvar sameInstance = caughtErr;\n\ncheckError.compatibleMessage(caughtErr, /TypeError$/); // true\ncheckError.compatibleMessage(caughtErr, 'I am a'); // true\ncheckError.compatibleMessage(caughtErr, /unicorn/); // false\ncheckError.compatibleMessage(caughtErr, 'I do not exist'); // false\n```\n\n#### .getConstructorName(errorLike)\n\n```js\nvar checkError = require('check-error');\n\nvar funcThatThrows = function() { throw new TypeError('I am a TypeError') };\nvar caughtErr;\n\ntry {\n  funcThatThrows();\n} catch(e) {\n  caughtErr = e;\n}\n\nvar sameInstance = caughtErr;\n\ncheckError.getConstructorName(caughtErr) // 'TypeError'\n```\n\n#### .getMessage(err)\n\n```js\nvar checkError = require('check-error');\n\nvar funcThatThrows = function() { throw new TypeError('I am a TypeError') };\nvar caughtErr;\n\ntry {\n  funcThatThrows();\n} catch(e) {\n  caughtErr = e;\n}\n\nvar sameInstance = caughtErr;\n\ncheckError.getMessage(caughtErr) // 'I am a TypeError'\n```\n",
  "readmeFilename": "README.md",
  "bugs": {
    "url": "https://github.com/chaijs/check-error/issues"
  },
  "_id": "check-error@2.1.1",
  "dist": {
    "shasum": "1ce4485626318b47e2707d3a7236a1ea189883e8"
  },
  "_from": "check-error@^2.1.1",
  "_resolved": "https://registry.npmjs.org/check-error/-/check-error-2.1.1.tgz"
}
